// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAttachmentsByConversation = `-- name: CountAttachmentsByConversation :one
SELECT COUNT(*)
FROM attachments a
INNER JOIN messages m ON a.message_id = m.id AND a.message_created_at = m.created_at
WHERE m.conversation_id = $1 AND (m.is_deleted = FALSE OR m.is_deleted IS NULL)
`

func (q *Queries) CountAttachmentsByConversation(ctx context.Context, conversationID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttachmentsByConversation, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (message_id, message_created_at, file_name, file_type, file_size, file_url, thumbnail_url, width, height, duration)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, message_id, message_created_at, file_name, file_type, file_size, file_url, thumbnail_url, width, height, duration, created_at
`

type CreateAttachmentParams struct {
	MessageID        uuid.UUID      `json:"message_id"`
	MessageCreatedAt time.Time      `json:"message_created_at"`
	FileName         string         `json:"file_name"`
	FileType         string         `json:"file_type"`
	FileSize         int64          `json:"file_size"`
	FileUrl          string         `json:"file_url"`
	ThumbnailUrl     sql.NullString `json:"thumbnail_url"`
	Width            sql.NullInt32  `json:"width"`
	Height           sql.NullInt32  `json:"height"`
	Duration         sql.NullInt32  `json:"duration"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createAttachment,
		arg.MessageID,
		arg.MessageCreatedAt,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.FileUrl,
		arg.ThumbnailUrl,
		arg.Width,
		arg.Height,
		arg.Duration,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.MessageCreatedAt,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.FileUrl,
		&i.ThumbnailUrl,
		&i.Width,
		&i.Height,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, message_id, message_created_at, file_name, file_type, file_size, file_url, thumbnail_url, width, height, duration, created_at
FROM attachments
WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.MessageCreatedAt,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.FileUrl,
		&i.ThumbnailUrl,
		&i.Width,
		&i.Height,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByConversation = `-- name: ListAttachmentsByConversation :many
SELECT a.id, a.message_id, a.message_created_at, a.file_name, a.file_type, a.file_size, a.file_url, a.thumbnail_url, a.width, a.height, a.duration, a.created_at
FROM attachments a
INNER JOIN messages m ON a.message_id = m.id AND a.message_created_at = m.created_at
WHERE m.conversation_id = $1 AND (m.is_deleted = FALSE OR m.is_deleted IS NULL)
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAttachmentsByConversationParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListAttachmentsByConversation(ctx context.Context, arg ListAttachmentsByConversationParams) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByConversation, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.MessageCreatedAt,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.FileUrl,
			&i.ThumbnailUrl,
			&i.Width,
			&i.Height,
			&i.Duration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByMessage = `-- name: ListAttachmentsByMessage :many
SELECT id, message_id, message_created_at, file_name, file_type, file_size, file_url, thumbnail_url, width, height, duration, created_at
FROM attachments
WHERE message_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAttachmentsByMessage(ctx context.Context, messageID uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.MessageCreatedAt,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.FileUrl,
			&i.ThumbnailUrl,
			&i.Width,
			&i.Height,
			&i.Duration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
