// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const archiveConversation = `-- name: ArchiveConversation :one
UPDATE conversations
SET is_archived = TRUE
WHERE id = $1
RETURNING id, type, name, description, avatar_url, creator_id, is_archived, last_message_at, created_at, updated_at
`

func (q *Queries) ArchiveConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, archiveConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatorID,
		&i.IsArchived,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countConversationsByUser = `-- name: CountConversationsByUser :one
SELECT COUNT(*) FROM conversations c
INNER JOIN conversation_participants cp ON c.id = cp.conversation_id
WHERE cp.user_id = $1 AND cp.left_at IS NULL
`

func (q *Queries) CountConversationsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConversationsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchConversationsByUser = `-- name: CountSearchConversationsByUser :one
SELECT COUNT(*) FROM conversations c
INNER JOIN conversation_participants cp ON c.id = cp.conversation_id
WHERE cp.user_id = $1 AND cp.left_at IS NULL
AND (
    (c.type IN ('group', 'channel') AND c.name ILIKE '%' || $2 || '%')
    OR
    (c.type = 'direct' AND EXISTS (
        SELECT 1 FROM conversation_participants cp2
        INNER JOIN users u ON u.id = cp2.user_id
        WHERE cp2.conversation_id = c.id
        AND cp2.user_id != $1
        AND cp2.left_at IS NULL
        AND u.username ILIKE '%' || $2 || '%'
    ))
)
`

type CountSearchConversationsByUserParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	SearchTerm sql.NullString `json:"search_term"`
}

func (q *Queries) CountSearchConversationsByUser(ctx context.Context, arg CountSearchConversationsByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchConversationsByUser, arg.UserID, arg.SearchTerm)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (type, name, description, avatar_url, creator_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, name, description, avatar_url, creator_id, is_archived, last_message_at, created_at, updated_at
`

type CreateConversationParams struct {
	Type        ConversationType `json:"type"`
	Name        sql.NullString   `json:"name"`
	Description sql.NullString   `json:"description"`
	AvatarUrl   sql.NullString   `json:"avatar_url"`
	CreatorID   uuid.NullUUID    `json:"creator_id"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.CreatorID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatorID,
		&i.IsArchived,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, type, name, description, avatar_url, creator_id, is_archived, last_message_at, created_at, updated_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatorID,
		&i.IsArchived,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsByUser = `-- name: ListConversationsByUser :many
SELECT c.id, c.type, c.name, c.description, c.avatar_url, c.creator_id, c.is_archived, c.last_message_at, c.created_at, c.updated_at
FROM conversations c
INNER JOIN conversation_participants cp ON c.id = cp.conversation_id
WHERE cp.user_id = $1 AND cp.left_at IS NULL
ORDER BY c.last_message_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListConversationsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListConversationsByUser(ctx context.Context, arg ListConversationsByUserParams) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.CreatorID,
			&i.IsArchived,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchConversationsByUser = `-- name: SearchConversationsByUser :many
SELECT c.id, c.type, c.name, c.description, c.avatar_url, c.creator_id, c.is_archived, c.last_message_at, c.created_at, c.updated_at
FROM conversations c
INNER JOIN conversation_participants cp ON c.id = cp.conversation_id
WHERE cp.user_id = $1 AND cp.left_at IS NULL
AND (
    (c.type IN ('group', 'channel') AND c.name ILIKE '%' || $4 || '%')
    OR
    (c.type = 'direct' AND EXISTS (
        SELECT 1 FROM conversation_participants cp2
        INNER JOIN users u ON u.id = cp2.user_id
        WHERE cp2.conversation_id = c.id
        AND cp2.user_id != $1
        AND cp2.left_at IS NULL
        AND u.username ILIKE '%' || $4 || '%'
    ))
)
ORDER BY c.last_message_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type SearchConversationsByUserParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	SearchTerm sql.NullString `json:"search_term"`
}

func (q *Queries) SearchConversationsByUser(ctx context.Context, arg SearchConversationsByUserParams) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, searchConversationsByUser,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.SearchTerm,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.CreatorID,
			&i.IsArchived,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveConversation = `-- name: UnarchiveConversation :one
UPDATE conversations
SET is_archived = FALSE
WHERE id = $1
RETURNING id, type, name, description, avatar_url, creator_id, is_archived, last_message_at, created_at, updated_at
`

func (q *Queries) UnarchiveConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, unarchiveConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatorID,
		&i.IsArchived,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations
SET name = $2, description = $3, avatar_url = $4
WHERE id = $1
RETURNING id, type, name, description, avatar_url, creator_id, is_archived, last_message_at, created_at, updated_at
`

type UpdateConversationParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, updateConversation,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatorID,
		&i.IsArchived,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
