// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countMessagesByConversation = `-- name: CountMessagesByConversation :one
SELECT COUNT(*) FROM messages
WHERE conversation_id = $1 AND (is_deleted = FALSE OR is_deleted IS NULL)
`

func (q *Queries) CountMessagesByConversation(ctx context.Context, conversationID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessagesByConversation, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchMessages = `-- name: CountSearchMessages :one
SELECT COUNT(*) FROM messages
WHERE conversation_id = $1
AND (is_deleted = FALSE OR is_deleted IS NULL)
AND to_tsvector('french', COALESCE(content, '')) @@ plainto_tsquery('french', $2)
`

type CountSearchMessagesParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
}

func (q *Queries) CountSearchMessages(ctx context.Context, arg CountSearchMessagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchMessages, arg.ConversationID, arg.PlaintoTsquery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, type, content, metadata, reply_to_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, conversation_id, sender_id, type, content, metadata, reply_to_id,
          is_edited, edited_at, is_deleted, deleted_at, created_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID             `json:"conversation_id"`
	SenderID       uuid.UUID             `json:"sender_id"`
	Type           NullMessageType       `json:"type"`
	Content        sql.NullString        `json:"content"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	ReplyToID      uuid.NullUUID         `json:"reply_to_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Type,
		arg.Content,
		arg.Metadata,
		arg.ReplyToID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Type,
		&i.Content,
		&i.Metadata,
		&i.ReplyToID,
		&i.IsEdited,
		&i.EditedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, conversation_id, sender_id, type, content, metadata, reply_to_id,
       is_edited, edited_at, is_deleted, deleted_at, created_at
FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Type,
		&i.Content,
		&i.Metadata,
		&i.ReplyToID,
		&i.IsEdited,
		&i.EditedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, sender_id, type, content, metadata, reply_to_id,
       is_edited, edited_at, is_deleted, deleted_at, created_at
FROM messages
WHERE conversation_id = $1 AND (is_deleted = FALSE OR is_deleted IS NULL)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMessagesByConversationParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListMessagesByConversation(ctx context.Context, arg ListMessagesByConversationParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByConversation, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Type,
			&i.Content,
			&i.Metadata,
			&i.ReplyToID,
			&i.IsEdited,
			&i.EditedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many
SELECT id, conversation_id, sender_id, type, content, metadata, reply_to_id,
       is_edited, edited_at, is_deleted, deleted_at, created_at
FROM messages
WHERE conversation_id = $1
AND (is_deleted = FALSE OR is_deleted IS NULL)
AND to_tsvector('french', COALESCE(content, '')) @@ plainto_tsquery('french', $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchMessagesParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, searchMessages,
		arg.ConversationID,
		arg.PlaintoTsquery,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Type,
			&i.Content,
			&i.Metadata,
			&i.ReplyToID,
			&i.IsEdited,
			&i.EditedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :one
UPDATE messages SET is_deleted = TRUE, deleted_at = NOW()
WHERE id = $1 AND (is_deleted = FALSE OR is_deleted IS NULL)
RETURNING id, conversation_id, sender_id, type, content, metadata, reply_to_id,
          is_edited, edited_at, is_deleted, deleted_at, created_at
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, softDeleteMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Type,
		&i.Content,
		&i.Metadata,
		&i.ReplyToID,
		&i.IsEdited,
		&i.EditedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE messages SET content = $3, is_edited = TRUE, edited_at = NOW()
WHERE id = $1 AND sender_id = $2 AND (is_deleted = FALSE OR is_deleted IS NULL)
RETURNING id, conversation_id, sender_id, type, content, metadata, reply_to_id,
          is_edited, edited_at, is_deleted, deleted_at, created_at
`

type UpdateMessageContentParams struct {
	ID       uuid.UUID      `json:"id"`
	SenderID uuid.UUID      `json:"sender_id"`
	Content  sql.NullString `json:"content"`
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateMessageContent, arg.ID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Type,
		&i.Content,
		&i.Metadata,
		&i.ReplyToID,
		&i.IsEdited,
		&i.EditedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}
