// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ConversationType string

const (
	ConversationTypeDirect  ConversationType = "direct"
	ConversationTypeGroup   ConversationType = "group"
	ConversationTypeChannel ConversationType = "channel"
)

func (e *ConversationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationType(s)
	case string:
		*e = ConversationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationType: %T", src)
	}
	return nil
}

type NullConversationType struct {
	ConversationType ConversationType `json:"conversation_type"`
	Valid            bool             `json:"valid"` // Valid is true if ConversationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationType) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationType), nil
}

type MessageType string

const (
	MessageTypeText   MessageType = "text"
	MessageTypeImage  MessageType = "image"
	MessageTypeFile   MessageType = "file"
	MessageTypeAudio  MessageType = "audio"
	MessageTypeVideo  MessageType = "video"
	MessageTypeSystem MessageType = "system"
)

func (e *MessageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageType(s)
	case string:
		*e = MessageType(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageType: %T", src)
	}
	return nil
}

type NullMessageType struct {
	MessageType MessageType `json:"message_type"`
	Valid       bool        `json:"valid"` // Valid is true if MessageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageType) Scan(value interface{}) error {
	if value == nil {
		ns.MessageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageType), nil
}

type Attachment struct {
	ID               uuid.UUID      `json:"id"`
	MessageID        uuid.UUID      `json:"message_id"`
	MessageCreatedAt time.Time      `json:"message_created_at"`
	FileName         string         `json:"file_name"`
	FileType         string         `json:"file_type"`
	FileSize         int64          `json:"file_size"`
	FileUrl          string         `json:"file_url"`
	ThumbnailUrl     sql.NullString `json:"thumbnail_url"`
	Width            sql.NullInt32  `json:"width"`
	Height           sql.NullInt32  `json:"height"`
	Duration         sql.NullInt32  `json:"duration"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type Conversation struct {
	ID            uuid.UUID        `json:"id"`
	Type          ConversationType `json:"type"`
	Name          sql.NullString   `json:"name"`
	Description   sql.NullString   `json:"description"`
	AvatarUrl     sql.NullString   `json:"avatar_url"`
	CreatorID     uuid.NullUUID    `json:"creator_id"`
	IsArchived    sql.NullBool     `json:"is_archived"`
	LastMessageAt sql.NullTime     `json:"last_message_at"`
	CreatedAt     sql.NullTime     `json:"created_at"`
	UpdatedAt     sql.NullTime     `json:"updated_at"`
}

type ConversationParticipant struct {
	ID                uuid.UUID      `json:"id"`
	ConversationID    uuid.UUID      `json:"conversation_id"`
	UserID            uuid.UUID      `json:"user_id"`
	Role              sql.NullString `json:"role"`
	Nickname          sql.NullString `json:"nickname"`
	IsMuted           sql.NullBool   `json:"is_muted"`
	MutedUntil        sql.NullTime   `json:"muted_until"`
	LastReadAt        sql.NullTime   `json:"last_read_at"`
	LastReadMessageID uuid.NullUUID  `json:"last_read_message_id"`
	JoinedAt          sql.NullTime   `json:"joined_at"`
	LeftAt            sql.NullTime   `json:"left_at"`
}

type Message struct {
	ID             uuid.UUID             `json:"id"`
	ConversationID uuid.UUID             `json:"conversation_id"`
	SenderID       uuid.UUID             `json:"sender_id"`
	Type           NullMessageType       `json:"type"`
	Content        sql.NullString        `json:"content"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	ReplyToID      uuid.NullUUID         `json:"reply_to_id"`
	IsEdited       sql.NullBool          `json:"is_edited"`
	EditedAt       sql.NullTime          `json:"edited_at"`
	IsDeleted      sql.NullBool          `json:"is_deleted"`
	DeletedAt      sql.NullTime          `json:"deleted_at"`
	CreatedAt      time.Time             `json:"created_at"`
}

type MessageReaction struct {
	ID               uuid.UUID    `json:"id"`
	MessageID        uuid.UUID    `json:"message_id"`
	MessageCreatedAt time.Time    `json:"message_created_at"`
	UserID           uuid.UUID    `json:"user_id"`
	Emoji            string       `json:"emoji"`
	CreatedAt        sql.NullTime `json:"created_at"`
}

type MessagesDefault struct {
	ID             uuid.UUID             `json:"id"`
	ConversationID uuid.UUID             `json:"conversation_id"`
	SenderID       uuid.UUID             `json:"sender_id"`
	Type           NullMessageType       `json:"type"`
	Content        sql.NullString        `json:"content"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	ReplyToID      uuid.NullUUID         `json:"reply_to_id"`
	IsEdited       sql.NullBool          `json:"is_edited"`
	EditedAt       sql.NullTime          `json:"edited_at"`
	IsDeleted      sql.NullBool          `json:"is_deleted"`
	DeletedAt      sql.NullTime          `json:"deleted_at"`
	CreatedAt      time.Time             `json:"created_at"`
}

type MessagesY2026m02 struct {
	ID             uuid.UUID             `json:"id"`
	ConversationID uuid.UUID             `json:"conversation_id"`
	SenderID       uuid.UUID             `json:"sender_id"`
	Type           NullMessageType       `json:"type"`
	Content        sql.NullString        `json:"content"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	ReplyToID      uuid.NullUUID         `json:"reply_to_id"`
	IsEdited       sql.NullBool          `json:"is_edited"`
	EditedAt       sql.NullTime          `json:"edited_at"`
	IsDeleted      sql.NullBool          `json:"is_deleted"`
	DeletedAt      sql.NullTime          `json:"deleted_at"`
	CreatedAt      time.Time             `json:"created_at"`
}

type MessagesY2026m03 struct {
	ID             uuid.UUID             `json:"id"`
	ConversationID uuid.UUID             `json:"conversation_id"`
	SenderID       uuid.UUID             `json:"sender_id"`
	Type           NullMessageType       `json:"type"`
	Content        sql.NullString        `json:"content"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	ReplyToID      uuid.NullUUID         `json:"reply_to_id"`
	IsEdited       sql.NullBool          `json:"is_edited"`
	EditedAt       sql.NullTime          `json:"edited_at"`
	IsDeleted      sql.NullBool          `json:"is_deleted"`
	DeletedAt      sql.NullTime          `json:"deleted_at"`
	CreatedAt      time.Time             `json:"created_at"`
}

type MessagesY2026m04 struct {
	ID             uuid.UUID             `json:"id"`
	ConversationID uuid.UUID             `json:"conversation_id"`
	SenderID       uuid.UUID             `json:"sender_id"`
	Type           NullMessageType       `json:"type"`
	Content        sql.NullString        `json:"content"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	ReplyToID      uuid.NullUUID         `json:"reply_to_id"`
	IsEdited       sql.NullBool          `json:"is_edited"`
	EditedAt       sql.NullTime          `json:"edited_at"`
	IsDeleted      sql.NullBool          `json:"is_deleted"`
	DeletedAt      sql.NullTime          `json:"deleted_at"`
	CreatedAt      time.Time             `json:"created_at"`
}

type PinnedMessage struct {
	ID               uuid.UUID    `json:"id"`
	ConversationID   uuid.UUID    `json:"conversation_id"`
	MessageID        uuid.UUID    `json:"message_id"`
	MessageCreatedAt time.Time    `json:"message_created_at"`
	PinnedBy         uuid.UUID    `json:"pinned_by"`
	PinnedAt         sql.NullTime `json:"pinned_at"`
}

type ReadReceipt struct {
	ID                uuid.UUID    `json:"id"`
	ConversationID    uuid.UUID    `json:"conversation_id"`
	UserID            uuid.UUID    `json:"user_id"`
	LastReadMessageID uuid.UUID    `json:"last_read_message_id"`
	LastReadAt        sql.NullTime `json:"last_read_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	DisplayName string         `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
