// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO conversation_participants (conversation_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, user_id, role, nickname, is_muted, muted_until, last_read_at, last_read_message_id, joined_at, left_at
`

type AddParticipantParams struct {
	ConversationID uuid.UUID      `json:"conversation_id"`
	UserID         uuid.UUID      `json:"user_id"`
	Role           sql.NullString `json:"role"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRowContext(ctx, addParticipant, arg.ConversationID, arg.UserID, arg.Role)
	var i ConversationParticipant
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Nickname,
		&i.IsMuted,
		&i.MutedUntil,
		&i.LastReadAt,
		&i.LastReadMessageID,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const countActiveParticipants = `-- name: CountActiveParticipants :one
SELECT COUNT(*) FROM conversation_participants
WHERE conversation_id = $1 AND left_at IS NULL
`

func (q *Queries) CountActiveParticipants(ctx context.Context, conversationID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveParticipants, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDirectConversationBetweenUsers = `-- name: GetDirectConversationBetweenUsers :one
SELECT c.id, c.type, c.name, c.description, c.avatar_url, c.creator_id, c.is_archived, c.last_message_at, c.created_at, c.updated_at
FROM conversations c
WHERE c.type = 'direct'
AND EXISTS (
    SELECT 1 FROM conversation_participants cp1
    WHERE cp1.conversation_id = c.id AND cp1.user_id = $1 AND cp1.left_at IS NULL
)
AND EXISTS (
    SELECT 1 FROM conversation_participants cp2
    WHERE cp2.conversation_id = c.id AND cp2.user_id = $2 AND cp2.left_at IS NULL
)
`

type GetDirectConversationBetweenUsersParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

func (q *Queries) GetDirectConversationBetweenUsers(ctx context.Context, arg GetDirectConversationBetweenUsersParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getDirectConversationBetweenUsers, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatorID,
		&i.IsArchived,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, conversation_id, user_id, role, nickname, is_muted, muted_until, last_read_at, last_read_message_id, joined_at, left_at FROM conversation_participants
WHERE conversation_id = $1 AND user_id = $2 AND left_at IS NULL
`

type GetParticipantParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRowContext(ctx, getParticipant, arg.ConversationID, arg.UserID)
	var i ConversationParticipant
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Nickname,
		&i.IsMuted,
		&i.MutedUntil,
		&i.LastReadAt,
		&i.LastReadMessageID,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const listParticipants = `-- name: ListParticipants :many
SELECT id, conversation_id, user_id, role, nickname, is_muted, muted_until, last_read_at, last_read_message_id, joined_at, left_at FROM conversation_participants
WHERE conversation_id = $1 AND left_at IS NULL
ORDER BY joined_at ASC
`

func (q *Queries) ListParticipants(ctx context.Context, conversationID uuid.UUID) ([]ConversationParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationParticipant
	for rows.Next() {
		var i ConversationParticipant
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.Nickname,
			&i.IsMuted,
			&i.MutedUntil,
			&i.LastReadAt,
			&i.LastReadMessageID,
			&i.JoinedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeParticipant = `-- name: RemoveParticipant :exec
UPDATE conversation_participants SET left_at = NOW()
WHERE conversation_id = $1 AND user_id = $2 AND left_at IS NULL
`

type RemoveParticipantParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.ExecContext(ctx, removeParticipant, arg.ConversationID, arg.UserID)
	return err
}
