// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pinned_messages.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPinnedMessage = `-- name: GetPinnedMessage :one
SELECT id, conversation_id, message_id, message_created_at, pinned_by, pinned_at
FROM pinned_messages
WHERE conversation_id = $1 AND message_id = $2
`

type GetPinnedMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	MessageID      uuid.UUID `json:"message_id"`
}

func (q *Queries) GetPinnedMessage(ctx context.Context, arg GetPinnedMessageParams) (PinnedMessage, error) {
	row := q.db.QueryRowContext(ctx, getPinnedMessage, arg.ConversationID, arg.MessageID)
	var i PinnedMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.MessageCreatedAt,
		&i.PinnedBy,
		&i.PinnedAt,
	)
	return i, err
}

const listPinnedMessages = `-- name: ListPinnedMessages :many
SELECT id, conversation_id, message_id, message_created_at, pinned_by, pinned_at
FROM pinned_messages
WHERE conversation_id = $1
ORDER BY pinned_at DESC
`

func (q *Queries) ListPinnedMessages(ctx context.Context, conversationID uuid.UUID) ([]PinnedMessage, error) {
	rows, err := q.db.QueryContext(ctx, listPinnedMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PinnedMessage
	for rows.Next() {
		var i PinnedMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.MessageID,
			&i.MessageCreatedAt,
			&i.PinnedBy,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinMessage = `-- name: PinMessage :one
INSERT INTO pinned_messages (conversation_id, message_id, message_created_at, pinned_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (conversation_id, message_id) DO NOTHING
RETURNING id, conversation_id, message_id, message_created_at, pinned_by, pinned_at
`

type PinMessageParams struct {
	ConversationID   uuid.UUID `json:"conversation_id"`
	MessageID        uuid.UUID `json:"message_id"`
	MessageCreatedAt time.Time `json:"message_created_at"`
	PinnedBy         uuid.UUID `json:"pinned_by"`
}

func (q *Queries) PinMessage(ctx context.Context, arg PinMessageParams) (PinnedMessage, error) {
	row := q.db.QueryRowContext(ctx, pinMessage,
		arg.ConversationID,
		arg.MessageID,
		arg.MessageCreatedAt,
		arg.PinnedBy,
	)
	var i PinnedMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.MessageID,
		&i.MessageCreatedAt,
		&i.PinnedBy,
		&i.PinnedAt,
	)
	return i, err
}

const unpinMessage = `-- name: UnpinMessage :exec
DELETE FROM pinned_messages
WHERE conversation_id = $1 AND message_id = $2
`

type UnpinMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	MessageID      uuid.UUID `json:"message_id"`
}

func (q *Queries) UnpinMessage(ctx context.Context, arg UnpinMessageParams) error {
	_, err := q.db.ExecContext(ctx, unpinMessage, arg.ConversationID, arg.MessageID)
	return err
}
