// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg AddParticipantParams) (ConversationParticipant, error)
	ArchiveConversation(ctx context.Context, id uuid.UUID) (Conversation, error)
	CountActiveParticipants(ctx context.Context, conversationID uuid.UUID) (int64, error)
	CountConversationsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountSearchConversationsByUser(ctx context.Context, arg CountSearchConversationsByUserParams) (int64, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	DeleteConversation(ctx context.Context, id uuid.UUID) error
	GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error)
	GetDirectConversationBetweenUsers(ctx context.Context, arg GetDirectConversationBetweenUsersParams) (Conversation, error)
	GetParticipant(ctx context.Context, arg GetParticipantParams) (ConversationParticipant, error)
	ListConversationsByUser(ctx context.Context, arg ListConversationsByUserParams) ([]Conversation, error)
	ListParticipants(ctx context.Context, conversationID uuid.UUID) ([]ConversationParticipant, error)
	RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error
	SearchConversationsByUser(ctx context.Context, arg SearchConversationsByUserParams) ([]Conversation, error)
	UnarchiveConversation(ctx context.Context, id uuid.UUID) (Conversation, error)
	UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error)
}

var _ Querier = (*Queries)(nil)
