// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addReaction = `-- name: AddReaction :one
INSERT INTO message_reactions (message_id, message_created_at, user_id, emoji)
VALUES ($1, $2, $3, $4)
ON CONFLICT (message_id, user_id, emoji) DO NOTHING
RETURNING id, message_id, message_created_at, user_id, emoji, created_at
`

type AddReactionParams struct {
	MessageID        uuid.UUID `json:"message_id"`
	MessageCreatedAt time.Time `json:"message_created_at"`
	UserID           uuid.UUID `json:"user_id"`
	Emoji            string    `json:"emoji"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (MessageReaction, error) {
	row := q.db.QueryRowContext(ctx, addReaction,
		arg.MessageID,
		arg.MessageCreatedAt,
		arg.UserID,
		arg.Emoji,
	)
	var i MessageReaction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.MessageCreatedAt,
		&i.UserID,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const listReactionsByMessage = `-- name: ListReactionsByMessage :many
SELECT id, message_id, message_created_at, user_id, emoji, created_at
FROM message_reactions
WHERE message_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListReactionsByMessage(ctx context.Context, messageID uuid.UUID) ([]MessageReaction, error) {
	rows, err := q.db.QueryContext(ctx, listReactionsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageReaction
	for rows.Next() {
		var i MessageReaction
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.MessageCreatedAt,
			&i.UserID,
			&i.Emoji,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM message_reactions
WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
	Emoji     string    `json:"emoji"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.ExecContext(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}
