// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read_receipts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getReadReceipt = `-- name: GetReadReceipt :one
SELECT id, conversation_id, user_id, last_read_message_id, last_read_at
FROM read_receipts
WHERE conversation_id = $1 AND user_id = $2
`

type GetReadReceiptParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetReadReceipt(ctx context.Context, arg GetReadReceiptParams) (ReadReceipt, error) {
	row := q.db.QueryRowContext(ctx, getReadReceipt, arg.ConversationID, arg.UserID)
	var i ReadReceipt
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.LastReadMessageID,
		&i.LastReadAt,
	)
	return i, err
}

const listReadReceipts = `-- name: ListReadReceipts :many
SELECT id, conversation_id, user_id, last_read_message_id, last_read_at
FROM read_receipts
WHERE conversation_id = $1
ORDER BY last_read_at DESC
`

func (q *Queries) ListReadReceipts(ctx context.Context, conversationID uuid.UUID) ([]ReadReceipt, error) {
	rows, err := q.db.QueryContext(ctx, listReadReceipts, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadReceipt
	for rows.Next() {
		var i ReadReceipt
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.LastReadMessageID,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReadReceipt = `-- name: UpsertReadReceipt :one
INSERT INTO read_receipts (conversation_id, user_id, last_read_message_id, last_read_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (conversation_id, user_id)
DO UPDATE SET last_read_message_id = EXCLUDED.last_read_message_id, last_read_at = NOW()
RETURNING id, conversation_id, user_id, last_read_message_id, last_read_at
`

type UpsertReadReceiptParams struct {
	ConversationID    uuid.UUID `json:"conversation_id"`
	UserID            uuid.UUID `json:"user_id"`
	LastReadMessageID uuid.UUID `json:"last_read_message_id"`
}

func (q *Queries) UpsertReadReceipt(ctx context.Context, arg UpsertReadReceiptParams) (ReadReceipt, error) {
	row := q.db.QueryRowContext(ctx, upsertReadReceipt, arg.ConversationID, arg.UserID, arg.LastReadMessageID)
	var i ReadReceipt
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.LastReadMessageID,
		&i.LastReadAt,
	)
	return i, err
}
